# -*- coding: utf-8 -*-
"""Funcoes_FASE3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0chRDwpnUDoEjb4lMF_NebJStW6t2Ic
"""

import re
import unicodedata

from pyspark.sql.functions import col ,when, count

def limpar_nome_coluna(nome):
    nome = unicodedata.normalize("NFKD", nome)

    nome = "".join(
        c for c in nome
        if not unicodedata.combining(c)
    )

    nome = re.sub(r"[^a-zA-Z0-9_]+", "_", nome)
    nome = re.sub(r"_+", "_", nome)
    nome = nome.strip("_")

    return nome.lower()

def verificar_nulos(df, spark):
    total_linhas = df.count()

    exprs = [
        count(
            when(
                col(c).isNull() | (col(c) == ""),
                1
            )
        ).alias(c)
        for c in df.columns
    ]

    linha = df.agg(*exprs).collect()[0]

    dados = [
        (
            c,
            linha[c],
            total_linhas - linha[c],
            round((linha[c] / total_linhas) * 100, 2)
        )
        for c in df.columns
    ]

    return spark.createDataFrame(
        dados,
        [
            "coluna",
            "qtd_nulos",
            "qtd_preenchidos",
            "percentual_nulos"
        ]
    )

